draw_networkkx_nodes() missing argument
Get error TypeError: draw_networkx_nodes() got an unexpected keyword argument 'with_labels'
Reason: 
nx.draw_networkkx_nodes() does not have "with_labels" argumet.